import type { DocumentRecord, EmployeeRecord, InvoiceRecord, LeaveRequestRecord } from "./types";

export const employees: EmployeeRecord[] = [
  {
    id: "emp-001",
    name: "Maya Demir",
    email: "maya.demir@example.com",
    role: "master_admin",
    title: "Head of People",
    department: "People",
    location: "Istanbul",
    managerId: null,
    startDate: "2021-02-01",
    profilePhotoUrl: null,
    holidayAllowance: 24,
    holidayRemaining: 18,
    sickDaysUsed: 1,
    unpaidLeaveUsed: 0,
    financialProfile: {
      currency: "EUR",
      monthlyRate: 7200,
      invoiceCycle: "monthly",
      contractType: "employment",
    },
  },
  {
    id: "emp-002",
    name: "Selin Kaya",
    email: "selin.kaya@example.com",
    role: "master_admin",
    title: "CEO",
    department: "Executive",
    location: "London",
    managerId: null,
    startDate: "2020-05-15",
    profilePhotoUrl: null,
    holidayAllowance: 24,
    holidayRemaining: 16,
    sickDaysUsed: 0,
    unpaidLeaveUsed: 0,
    financialProfile: {
      currency: "EUR",
      monthlyRate: 12000,
      invoiceCycle: "monthly",
      contractType: "employment",
    },
  },
  {
    id: "emp-003",
    name: "Alessandro Rossi",
    email: "alessandro.rossi@example.com",
    role: "manager",
    title: "Engineering Manager",
    department: "Engineering",
    location: "Milan",
    managerId: "emp-002",
    startDate: "2022-01-10",
    profilePhotoUrl: null,
    holidayAllowance: 22,
    holidayRemaining: 12,
    sickDaysUsed: 2,
    unpaidLeaveUsed: 0,
    financialProfile: {
      currency: "EUR",
      monthlyRate: 8300,
      invoiceCycle: "monthly",
      contractType: "contractor",
    },
  },
  {
    id: "emp-004",
    name: "Alessandro Bianchi",
    email: "alessandro.bianchi@example.com",
    role: "manager",
    title: "Operations Manager",
    department: "Operations",
    location: "Rome",
    managerId: "emp-002",
    startDate: "2022-03-14",
    profilePhotoUrl: null,
    holidayAllowance: 22,
    holidayRemaining: 15,
    sickDaysUsed: 1,
    unpaidLeaveUsed: 1,
    financialProfile: {
      currency: "EUR",
      monthlyRate: 7900,
      invoiceCycle: "monthly",
      contractType: "contractor",
    },
  },
  {
    id: "emp-005",
    name: "Sofia Marino",
    email: "sofia.marino@example.com",
    role: "employee",
    title: "Product Designer",
    department: "Product",
    location: "Florence",
    managerId: "emp-003",
    startDate: "2023-09-01",
    profilePhotoUrl: null,
    holidayAllowance: 20,
    holidayRemaining: 13,
    sickDaysUsed: 1,
    unpaidLeaveUsed: 0,
    financialProfile: {
      currency: "EUR",
      monthlyRate: 5400,
      invoiceCycle: "monthly",
      contractType: "contractor",
    },
  },
  {
    id: "emp-006",
    name: "Luca Ferri",
    email: "luca.ferri@example.com",
    role: "employee",
    title: "Frontend Engineer",
    department: "Engineering",
    location: "Turin",
    managerId: "emp-003",
    startDate: "2024-04-08",
    profilePhotoUrl: null,
    holidayAllowance: 20,
    holidayRemaining: 9,
    sickDaysUsed: 3,
    unpaidLeaveUsed: 0,
    financialProfile: {
      currency: "EUR",
      monthlyRate: 6100,
      invoiceCycle: "monthly",
      contractType: "contractor",
    },
  },
  {
    id: "emp-007",
    name: "Elena Conte",
    email: "elena.conte@example.com",
    role: "employee",
    title: "People Operations Specialist",
    department: "People",
    location: "Istanbul",
    managerId: "emp-004",
    startDate: "2023-11-20",
    profilePhotoUrl: null,
    holidayAllowance: 20,
    holidayRemaining: 17,
    sickDaysUsed: 0,
    unpaidLeaveUsed: 0,
    financialProfile: {
      currency: "EUR",
      monthlyRate: 4700,
      invoiceCycle: "monthly",
      contractType: "employment",
    },
  },
];

export const leaveRequests: LeaveRequestRecord[] = [
  {
    id: "leave-101",
    employeeId: "emp-005",
    kind: "holiday",
    status: "pending",
    from: "2026-05-06",
    to: "2026-05-10",
    days: 3,
    requestedAt: "2026-04-15",
    reviewerId: null,
    decidedAt: null,
    slackThreadId: "slack-thread-001",
  },
  {
    id: "leave-102",
    employeeId: "emp-006",
    kind: "holiday",
    status: "approved",
    from: "2026-04-27",
    to: "2026-04-30",
    days: 4,
    requestedAt: "2026-04-08",
    reviewerId: "emp-003",
    decidedAt: "2026-04-09",
    slackThreadId: "slack-thread-002",
  },
  {
    id: "leave-103",
    employeeId: "emp-007",
    kind: "sick",
    status: "approved",
    from: "2026-04-16",
    to: "2026-04-17",
    days: 2,
    requestedAt: "2026-04-16",
    reviewerId: "emp-004",
    decidedAt: "2026-04-16",
    slackThreadId: "slack-thread-003",
  },
  {
    id: "leave-104",
    employeeId: "emp-004",
    kind: "unpaid",
    status: "rejected",
    from: "2026-05-20",
    to: "2026-05-22",
    days: 3,
    requestedAt: "2026-04-01",
    reviewerId: "emp-001",
    decidedAt: "2026-04-02",
    slackThreadId: "slack-thread-004",
  },
];

export const documents: DocumentRecord[] = [
  {
    id: "doc-201",
    employeeId: "emp-005",
    kind: "contract",
    status: "approved",
    title: "Contractor Agreement",
    period: "2025-2026",
    amount: null,
    currency: null,
    issuedAt: "2025-09-01",
    privateStorageKey: "contracts/emp-005/2025-contractor-agreement.pdf",
  },
  {
    id: "doc-202",
    employeeId: "emp-005",
    kind: "invoice",
    status: "approved",
    title: "Monthly Invoice",
    period: "March 2026",
    amount: 5400,
    currency: "EUR",
    issuedAt: "2026-03-31",
    privateStorageKey: "invoices/emp-005/2026-03.pdf",
  },
  {
    id: "doc-203",
    employeeId: "emp-006",
    kind: "invoice",
    status: "pending",
    title: "Monthly Invoice",
    period: "March 2026",
    amount: 6100,
    currency: "EUR",
    issuedAt: "2026-03-31",
    privateStorageKey: "invoices/emp-006/2026-03.pdf",
  },
  {
    id: "doc-204",
    employeeId: "emp-007",
    kind: "contract",
    status: "approved",
    title: "Employment Contract",
    period: "2025-2026",
    amount: null,
    currency: null,
    issuedAt: "2025-11-20",
    privateStorageKey: "contracts/emp-007/2025-employment-contract.pdf",
  },
  {
    id: "doc-205",
    employeeId: "emp-006",
    kind: "official",
    status: "approved",
    title: "Residence Registration",
    period: "2026",
    amount: null,
    currency: null,
    issuedAt: "2026-02-12",
    privateStorageKey: "official/emp-006/2026-residence-registration.pdf",
  },
  {
    id: "doc-206",
    employeeId: "emp-003",
    kind: "private",
    status: "rejected",
    title: "Private HR Note",
    period: "Q1 2026",
    amount: null,
    currency: null,
    issuedAt: "2026-03-08",
    privateStorageKey: "private/emp-003/2026-q1-note.pdf",
  },
];

export const invoices: InvoiceRecord[] = [
  {
    id: "inv-emp-003-march-2026",
    employeeId: "emp-003",
    period: "March 2026",
    amount: 8300,
    currency: "EUR",
    status: "paid",
    generatedAt: "2026-03-31",
    pdfStorageKey: "invoices/emp-003/march-2026.pdf",
  },
  {
    id: "inv-emp-004-march-2026",
    employeeId: "emp-004",
    period: "March 2026",
    amount: 7900,
    currency: "EUR",
    status: "unpaid",
    generatedAt: "2026-03-31",
    pdfStorageKey: "invoices/emp-004/march-2026.pdf",
  },
  {
    id: "inv-emp-005-march-2026",
    employeeId: "emp-005",
    period: "March 2026",
    amount: 5400,
    currency: "EUR",
    status: "paid",
    generatedAt: "2026-03-31",
    pdfStorageKey: "invoices/emp-005/march-2026.pdf",
  },
  {
    id: "inv-emp-006-april-2026",
    employeeId: "emp-006",
    period: "April 2026",
    amount: 6100,
    currency: "EUR",
    status: "unpaid",
    generatedAt: "2026-04-22",
    pdfStorageKey: "invoices/emp-006/april-2026.pdf",
  },
];
